# Generated by Django 6.0.6 on 2026-06-22 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Birthday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Необязательное поле",
                        max_length=20,
                        verbose_name="Фамилия",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
            ],
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "birthday_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="birthday.birthday",
                    ),
                ),
            ],
            bases=("birthday.birthday",),
        ),
    ]
